create table customers (
	ssn VARCHAR(50) primary key,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	country VARCHAR(50)
);
insert into customers (ssn, first_name, last_name, country) values ('533-51-7479', 'Tonnie', 'Favela', 'China');
insert into customers (ssn, first_name, last_name, country) values ('394-83-4315', 'Amye', 'Lambie', 'Indonesia');
insert into customers (ssn, first_name, last_name, country) values ('654-17-8892', 'Hyatt', 'Penton', 'China');
insert into customers (ssn, first_name, last_name, country) values ('673-44-1837', 'Nadya', 'Demicoli', 'Poland');
insert into customers (ssn, first_name, last_name, country) values ('781-12-3757', 'Traci', 'Twiname', 'Palestinian Territory');
insert into customers (ssn, first_name, last_name, country) values ('445-64-8646', 'Derron', 'Tomowicz', 'China');
insert into customers (ssn, first_name, last_name, country) values ('102-07-7559', 'Colline', 'Eastlake', 'Russia');
insert into customers (ssn, first_name, last_name, country) values ('382-13-6645', 'Cordie', 'Crowcum', 'Lebanon');
insert into customers (ssn, first_name, last_name, country) values ('897-08-2799', 'Charmain', 'Elms', 'Philippines');
insert into customers (ssn, first_name, last_name, country) values ('899-52-6754', 'Ranna', 'Ibarra', 'Slovenia');
insert into customers (ssn, first_name, last_name, country) values ('796-03-6552', 'Ewen', 'Magog', 'China');
insert into customers (ssn, first_name, last_name, country) values ('113-65-4482', 'Ardra', 'Grzegorzewski', 'China');
insert into customers (ssn, first_name, last_name, country) values ('805-83-5368', 'Heriberto', 'Whiten', 'Afghanistan');
insert into customers (ssn, first_name, last_name, country) values ('632-41-0977', 'Ulises', 'Corbyn', 'Republic of the Congo');
insert into customers (ssn, first_name, last_name, country) values ('295-61-9192', 'Yoshiko', 'Pays', 'Indonesia');
insert into customers (ssn, first_name, last_name, country) values ('519-70-6606', 'Ag', 'Bird', 'Philippines');
insert into customers (ssn, first_name, last_name, country) values ('596-84-2302', 'Melosa', 'Veall', 'China');
insert into customers (ssn, first_name, last_name, country) values ('180-24-3126', 'Melodee', 'Marjoribanks', 'China');
insert into customers (ssn, first_name, last_name, country) values ('191-03-9415', 'Rania', 'Krolle', 'Peru');
insert into customers (ssn, first_name, last_name, country) values ('310-44-8745', 'Erastus', 'Millican', 'Indonesia');
insert into customers (ssn, first_name, last_name, country) values ('206-46-1350', 'Verine', 'Fones', 'China');
insert into customers (ssn, first_name, last_name, country) values ('633-93-8679', 'Alisun', 'Eckels', 'Czech Republic');
insert into customers (ssn, first_name, last_name, country) values ('487-70-4750', 'Haily', 'Tort', 'Morocco');
insert into customers (ssn, first_name, last_name, country) values ('565-33-7174', 'Josselyn', 'Muneely', 'Philippines');
insert into customers (ssn, first_name, last_name, country) values ('340-90-3238', 'Raine', 'Cornfoot', 'Indonesia');
insert into customers (ssn, first_name, last_name, country) values ('558-28-7190', 'Lon', 'Circuit', 'Sweden');
insert into customers (ssn, first_name, last_name, country) values ('590-99-9318', 'Stephen', 'Camosso', 'China');
insert into customers (ssn, first_name, last_name, country) values ('366-28-5001', 'Lenka', 'Reignolds', 'Venezuela');
insert into customers (ssn, first_name, last_name, country) values ('454-36-7506', 'Hanna', 'Blanc', 'China');
insert into customers (ssn, first_name, last_name, country) values ('613-29-8680', 'Yorgos', 'Greenfield', 'Brazil');
insert into customers (ssn, first_name, last_name, country) values ('607-92-2375', 'Raimondo', 'Tarr', 'France');
insert into customers (ssn, first_name, last_name, country) values ('184-98-4736', 'Ronny', 'Pugh', 'Indonesia');
insert into customers (ssn, first_name, last_name, country) values ('110-09-3589', 'Elisa', 'Pottie', 'Kosovo');
insert into customers (ssn, first_name, last_name, country) values ('386-85-7651', 'Alfie', 'Mousdall', 'Nigeria');
insert into customers (ssn, first_name, last_name, country) values ('819-40-0411', 'Denys', 'Mattam', 'France');
insert into customers (ssn, first_name, last_name, country) values ('367-89-0746', 'Morry', 'Legrave', 'China');
insert into customers (ssn, first_name, last_name, country) values ('182-25-8356', 'Karim', 'Nare', 'Indonesia');
insert into customers (ssn, first_name, last_name, country) values ('712-81-6413', 'Valli', 'Amberg', 'Indonesia');
insert into customers (ssn, first_name, last_name, country) values ('122-34-0466', 'Rozele', 'Leathart', 'Russia');
insert into customers (ssn, first_name, last_name, country) values ('613-41-1916', 'Maurise', 'Claypoole', 'Burkina Faso');
insert into customers (ssn, first_name, last_name, country) values ('279-04-0443', 'Clayborne', 'Wimpenny', 'Indonesia');
insert into customers (ssn, first_name, last_name, country) values ('383-34-8678', 'Bax', 'Tortice', 'Colombia');
insert into customers (ssn, first_name, last_name, country) values ('436-54-3319', 'Brandon', 'Lang', 'Colombia');
insert into customers (ssn, first_name, last_name, country) values ('103-23-9972', 'Rycca', 'Wade', 'China');
insert into customers (ssn, first_name, last_name, country) values ('252-75-8362', 'Angelika', 'Keilty', 'Peru');
insert into customers (ssn, first_name, last_name, country) values ('476-01-8665', 'Levi', 'Otley', 'Indonesia');
insert into customers (ssn, first_name, last_name, country) values ('749-17-4694', 'Agustin', 'Corthes', 'Indonesia');
insert into customers (ssn, first_name, last_name, country) values ('579-45-8723', 'Alvy', 'Garmons', 'Portugal');
insert into customers (ssn, first_name, last_name, country) values ('686-26-7419', 'Alexandro', 'Inchan', 'Philippines');
insert into customers (ssn, first_name, last_name, country) values ('685-11-8884', 'Bianka', 'Kyles', 'Portugal');
insert into customers (ssn, first_name, last_name, country) values ('739-73-4891', 'Nicolle', 'Westfield', 'Indonesia');
insert into customers (ssn, first_name, last_name, country) values ('692-52-8329', 'Roxanna', 'Sitford', 'Canada');
insert into customers (ssn, first_name, last_name, country) values ('815-42-1726', 'Tommie', 'Kynston', 'Brazil');
insert into customers (ssn, first_name, last_name, country) values ('613-18-0592', 'Myer', 'Noe', 'United States');
insert into customers (ssn, first_name, last_name, country) values ('215-54-5791', 'Franky', 'O'' Mahony', 'China');
insert into customers (ssn, first_name, last_name, country) values ('650-20-2886', 'Olva', 'Snuggs', 'France');
insert into customers (ssn, first_name, last_name, country) values ('155-36-9540', 'Kasper', 'Charles', 'China');
insert into customers (ssn, first_name, last_name, country) values ('252-43-8282', 'Dur', 'Semble', 'Indonesia');
insert into customers (ssn, first_name, last_name, country) values ('778-79-8733', 'Clarine', 'Crocetto', 'Democratic Republic of the Congo');
insert into customers (ssn, first_name, last_name, country) values ('638-65-8230', 'Emilio', 'Calcutt', 'Indonesia');
insert into customers (ssn, first_name, last_name, country) values ('853-32-8644', 'Margaret', 'De Filippo', 'Thailand');
insert into customers (ssn, first_name, last_name, country) values ('555-26-0032', 'Edy', 'Dominka', 'Philippines');
insert into customers (ssn, first_name, last_name, country) values ('331-82-2418', 'Hinze', 'Kondratovich', 'Philippines');
insert into customers (ssn, first_name, last_name, country) values ('694-99-6887', 'Cad', 'Ellar', 'Peru');
insert into customers (ssn, first_name, last_name, country) values ('702-30-1539', 'Maegan', 'Plumley', 'China');
insert into customers (ssn, first_name, last_name, country) values ('582-85-1358', 'Anica', 'Lotwich', 'Poland');
insert into customers (ssn, first_name, last_name, country) values ('227-15-3244', 'Marrilee', 'Maunton', 'Indonesia');
insert into customers (ssn, first_name, last_name, country) values ('361-60-9182', 'Sarine', 'Martinie', 'Mongolia');
insert into customers (ssn, first_name, last_name, country) values ('233-80-2389', 'Hyman', 'Wallsam', 'Mauritius');
insert into customers (ssn, first_name, last_name, country) values ('594-36-4433', 'Leisha', 'Chezier', 'Philippines');
insert into customers (ssn, first_name, last_name, country) values ('435-48-0119', 'Grove', 'Wigfield', 'Peru');
insert into customers (ssn, first_name, last_name, country) values ('236-36-0062', 'Enrica', 'Rutherford', 'France');
insert into customers (ssn, first_name, last_name, country) values ('793-77-0816', 'Donella', 'Ary', 'Ukraine');
insert into customers (ssn, first_name, last_name, country) values ('831-69-7819', 'Ashien', 'Tomik', 'Philippines');
insert into customers (ssn, first_name, last_name, country) values ('494-96-8172', 'Jackquelin', 'Bon', 'China');
insert into customers (ssn, first_name, last_name, country) values ('705-79-1805', 'Paten', 'Schwandermann', 'China');
insert into customers (ssn, first_name, last_name, country) values ('450-49-8569', 'Berte', 'Rives', 'Indonesia');
insert into customers (ssn, first_name, last_name, country) values ('786-84-9803', 'Bonita', 'Varlow', 'Slovenia');
insert into customers (ssn, first_name, last_name, country) values ('173-49-0885', 'Alec', 'Eardley', 'Sweden');
insert into customers (ssn, first_name, last_name, country) values ('447-35-1212', 'Link', 'Ommundsen', 'Mongolia');
insert into customers (ssn, first_name, last_name, country) values ('642-13-6565', 'Shane', 'Curteis', 'Kazakhstan');
insert into customers (ssn, first_name, last_name, country) values ('572-99-8129', 'Inez', 'Gash', 'China');
insert into customers (ssn, first_name, last_name, country) values ('478-09-8143', 'Lanita', 'Pedri', 'Indonesia');
insert into customers (ssn, first_name, last_name, country) values ('685-31-9716', 'Nancey', 'Chevolleau', 'Poland');
insert into customers (ssn, first_name, last_name, country) values ('696-52-1259', 'Karim', 'Klaggeman', 'Russia');
insert into customers (ssn, first_name, last_name, country) values ('333-91-3331', 'Martha', 'Burnup', 'Belize');
insert into customers (ssn, first_name, last_name, country) values ('722-59-6507', 'Shandee', 'Pate', 'China');
insert into customers (ssn, first_name, last_name, country) values ('145-81-4108', 'Cosette', 'Roussel', 'Portugal');
insert into customers (ssn, first_name, last_name, country) values ('386-42-2725', 'Cull', 'Gytesham', 'Czech Republic');
insert into customers (ssn, first_name, last_name, country) values ('699-47-5773', 'Tymothy', 'Trout', 'Afghanistan');
insert into customers (ssn, first_name, last_name, country) values ('152-02-1352', 'Callida', 'Flamank', 'China');
insert into customers (ssn, first_name, last_name, country) values ('472-70-4499', 'Nelson', 'Spore', 'China');
insert into customers (ssn, first_name, last_name, country) values ('331-57-4447', 'Lem', 'Cristofalo', 'Tunisia');
insert into customers (ssn, first_name, last_name, country) values ('855-56-3895', 'Celestia', 'Willimot', 'Japan');
insert into customers (ssn, first_name, last_name, country) values ('156-46-2890', 'Alverta', 'MacTrustie', 'Cuba');
insert into customers (ssn, first_name, last_name, country) values ('861-75-3650', 'Imojean', 'De Nisco', 'Costa Rica');
insert into customers (ssn, first_name, last_name, country) values ('750-57-5989', 'Corissa', 'Carwithen', 'Yemen');
insert into customers (ssn, first_name, last_name, country) values ('554-74-2585', 'Beverly', 'Clashe', 'China');
insert into customers (ssn, first_name, last_name, country) values ('438-97-6179', 'Lauren', 'Grunbaum', 'China');
insert into customers (ssn, first_name, last_name, country) values ('194-62-5568', 'Burtie', 'Ligerton', 'Afghanistan');
